---
- name: linuxacademy puppet hands on labs
  hosts: pe_labs
  remote_user: cloud_user
  become: yes

  tasks:
  - include_vars: inventory/vault
  - include_vars: "inventory/vars/{{ ansible_distribution }}/pe_vars.yml"

  - name: install base packages
    action: >
      {{ ansible_pkg_mgr }} name={{packages}} state=present
    vars:
      packages:
      - curl

  - name: Puppet Master Role
    import_role:
      name: pe_master
    tags: pe_master
    when: puppet_role == "pe_master"
  - name: Puppet Node Role
    import_role:
      name: pe_node
    tags: pe_node
    when: puppet_role == "pe_node"
