---
- name: linuxacademy puppet hands on labs
  hosts: pe_labs
  remote_user: cloud_user
  become: yes

  tasks:
  - name: Gather OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
    - "inventory/vars/{{ ansible_distribution }}/vars.yml"

  - name: Gather vault variables
    include_vars: inventory/vault

  - name: install base packages
    action: >
      {{ ansible_pkg_mgr }} name={{packages}} state=present
    vars:
      packages:
      - curl
      - vim


  - name: Puppet Master Role
    import_role:
      name: pe_master
    tags: pe_master
    when: puppet_role == "pe_master"
  - name: Puppet Node Role
    import_role:
      name: pe_node
    tags: pe_node
    when: puppet_role == "pe_node"
