---
- name: linuxacademy puppet hands on labs
  hosts: puppet_labs
  remote_user: cloud_user
  become: yes

  tasks:
  - name: Gather OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
    - "inventory/vars/{{ ansible_distribution }}/vars.yml"

  - name: Gather vault variables
    include_vars: inventory/vault

  - name: install base packages
    action: >
      {{ ansible_pkg_mgr }} name=curl state=present


  - name: Puppet Master Role
    import_role:
      name: puppet_master
    tags: master
    when: puppet_role == "master"
  - name: Puppet Node Role
    import_role:
      name: puppet_node
    tags: node
    when: puppet_role == "node"
