all:
  hosts:
    pe-master-1:
    pe-node-1:
    pe-node-2:
  children:
    pe_labs:
      hosts:
        pe-master-1:
        pe-node-1:
        pe-node-2:
      vars:
        master_fqdn: swray1c.mylabserver.com
        master_ip: 172.31.39.165
    pe_masters:
      hosts: 
        pe-master-1:
      vars:
        puppet_role: pe_master
    pe_nodes:
      hosts:
        pe-node-1:
        pe-node-2:
      vars:
        puppet_role: pe_node


