---
- name: Set up hosts files
  lineinfile:
    path: /etc/hosts
    line: "{{ master_ip }} {{ master_fqdn }} puppet"

##################################
# Install Puppet Opensource Agents
- name: Install Puppet Opensource repo
  yum:
    name: "{{ puppet_opensource_url }}"
    state: present

- name: Install Puppet Opensource package
  yum:
    name: puppet-agent
    state: present

- name: Puppet Opensource sudoers
  lineinfile:
    path: /etc/sudoers.d/extra
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin'
    create: true
    owner: root
    group: root
    mode: 0440

