---
- name: Gather vault variables
  include_vars: vars/vault

- name: Set up hosts files
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 localhost'
    line: "127.0.0.1 {{ master_fqdn }} localhost"

- name: Download puppet tarball
  get_url:
    url: "{{ puppet_enterprise_url }}"
    dest: "/home/cloud_user/{{ puppet_enterprise_tarball }}"
    owner: cloud_user
    group: cloud_user

- name: Unpack puppet tarball
  unarchive:
    remote_src: yes
    src: "/home/cloud_user/{{ puppet_enterprise_tarball }}"
    dest: /home/cloud_user/
    creates: "/home/cloud_user/{{ puppet_enterprise_package }}"
    owner: cloud_user
    group: cloud_user

- name: Put pe.conf file in place
  template:
    src: master_pe.conf.j2
    dest: "/home/cloud_user/{{ puppet_enterprise_package }}/master_pe.conf"
    owner: cloud_user
    group: cloud_user

- name: Run pe installer with conf file
  command: "/home/cloud_user/{{ puppet_enterprise_package }}/puppet-enterprise-installer -c /home/cloud_user/{{ puppet_enterprise_package }}/master_pe.conf"
  args:
    creates: /opt/puppetlabs/

- name: Initial Puppet run on master
  command: /opt/puppetlabs/bin/puppet agent -t
  ignore_errors: true
  register: puppet_agent

- name: Install Puppet Opensource deb
  apt:
    deb: "{{ puppet_opensource_url }}"
  register: deb_installed

- name: Update apt cache
  apt:
    update_cache: yes
  when: deb_installed
  
- name: Install Puppet development kit
  apt:
    name: pdk
    state: present

- name: Set up deploy key
  command: "ssh-keygen -t rsa -b 2048 -P '' -f /etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa"
  args:
    creates: /etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa
  register: key_generated

- name: Create deploy key
  openssh_keypair:
    path: /etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa
    size: 2048
    type: rsa
  register: deploy_key

- name: Show public key
  debug:
    msg: "{{ deploy_key.public_key }}"
  when: deploy_key
    
